# ==================== ????? ====================
spring.datasource.url=jdbc:mysql://localhost:3306/yiyang_platform?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==================== MyBatis ???? ====================
# XML ???????classpath ?? * ???? jar ???????
mybatis.mapper-locations=classpath*:mapper/*.xml

# ==================== configuration ??? ====================
# ???????????user_name -> userName????????
mybatis.configuration.map-underscore-to-camel-case=true

# SQL ??????????????? Slf4jImpl?
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

